name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: action2thefuture/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 1b376a96ccc97ce5fbeea59836e8d5e3
          TIMEZONE: Asia/Seoul
